version: '3.8'

services:
  # PostgresSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: ch4nge_postgres
    environment:
      POSTGRES_USER: eco_user
      POSTGRES_PASSWORD: eco_1234
      POSTGRES_DB: eco_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eco_user -d eco_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ch4nge_network

  # Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ch4nge_api
    environment:
      - ENVIRONMENT=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=eco_user
      - DB_PASSWORD=eco_1234
      - DB_NAME=eco_db
      - DB_SSLMODE=disable
      - SERVER_PORT=8080
      - SERVER_HOST=0.0.0.0
      - JWT_SECRET=your-development-jwt-secret-key
      - ADMIN_PASSWORD=admin123
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - uploads_data:/app/uploads  # Persistent uploads storage
    networks:
      - ch4nge_network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  uploads_data:
    driver: local

networks:
  ch4nge_network:
    driver: bridge